### ISSUE TITLE
save_object.php

### ISSUE THREAD

**Issue by juanvallejo** [calebsevern/Flour#1]
Hey Caleb,

Haven't been in touch in a while, saw this update on my feed so I thought I'd take a look!

Saw the TODO on this file and thought I'd add.

> Needs to handle generic object types rather than hardcorded.
> Main issue is having a dynamic number of attributes to save

I assume by this you mean being able to handle a different amount of columns depending on the type of 'object'. A way I could think of solving this would be to add each of the object's attributes to an array inside of the JSON object you POST to the server:  

``` js
({
    type:       'object-type', 
    attributes: [
        {attr1: 'somevalue'},
        {attr2: 'someothervalue'}
    ]
}).
```

Then, on the PHP side, grab the $_POST['attributes'] string, do json_decode() on it, and construct that part of your mysql string by iterating through the list:

``` php

// decode the javascript array into a php array
$attributes       = json_decode($_POST['attributes']); 
$updateQuery      = "UPDATE `table_name` SET ";
$attributeCount   = 0;

// iterate through each of the posted attributes
foreach($attributes as $attributeName => $attributeValue) {

    // stitch the SET part of the mysql query
    $updateQuery .= $attributeName . "=" . "'" . $attributeValue . "'";

    // add comma to end of current piece of query if not the last one
    if($attributeCount != count($attributes) - 1) {
         $updateQuery .= ",";
    }

    $attributeCount++;

}

$updateQuery .= " WHERE ...";
```

I haven't tested any of this, but hopefully at the end of it, you'll have your $updateQuery looking something like this:

``` php
UPDATE `table_name` SET attr1='somevalue',attr2='someothervalue' WHERE ...
```

Hope this somewhat helps!

Also, I saw you on the list of people going to the VCU hackathon last semester, but didn't see you there, I'll be going to the dominion enterprises one in February, let me know if you'll be there!

**Comment by calebsevern** [comment]
Hey Juan,

I had that same idea; it wasn't compatible with the statement I was using:

``` php
$stmt->bind_param("ss", $val1, $val2);
```

The first though would be to build the type string ("ss") and collect the values, putting them all in a big array, which you could then pass off to bind_param. Unfortunately, bind_param doesn't accept arrays like that out of the box.

What might work is using PDOStatement::bindParam to bind an indefinite number of variables (you'll still have to build the statement though):

``` php
#You get the idea
foreach ($attributes as $k=> &$v) {
    $stmt->bindParam($k, $v);
```

Haven't tried it yet - you're welcome to push any changes you like though. 

I couldn't make it to the VCU one, but I'll see you in February!

**Comment by juanvallejo** [comment]
Ah, I should have explained I was forming the entire query, filling all of its parameters, on the loop itself rather than using `bind_param` to add them later, but I'm glad you resolved the issue nonetheless. I'll be happy to contribute once I find some free time again haha
